version = "1.0"

[metadata]

[environment]
build_timeout_sec = 600.0
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
POCHI_LOG = "debug"
POCHI_API_KEY = "${POCHI_API_KEY}"
# Add more environment variables requried
TIGRIS_STORAGE_ACCESS_KEY_ID = "${TIGRIS_STORAGE_ACCESS_KEY_ID}"
TIGRIS_STORAGE_SECRET_ACCESS_KEY = "${TIGRIS_STORAGE_SECRET_ACCESS_KEY}"
AWS_ENDPOINT_URL_S3 = "https://t3.storage.dev"

[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 600.0

[verifier.env]
POCHI_LOG = "debug"
# Add more environment variables requried
TIGRIS_STORAGE_ACCESS_KEY_ID = "${TIGRIS_STORAGE_ACCESS_KEY_ID}"
TIGRIS_STORAGE_SECRET_ACCESS_KEY = "${TIGRIS_STORAGE_SECRET_ACCESS_KEY}"
AWS_ENDPOINT_URL_S3 = "https://t3.storage.dev"

[solution.env]
